### ISSUE TITLE
Unconfirmed Account Cleanup

### ISSUE THREAD

**Issue by Klona13** [rr-/trcustoms#109]
If an account is Pending activation + Email UNCONFIRMED.
It is deleted after the 6 hour check.

```
User.objects.filter(is_active=False, is_email_confirmed=False, is_activation_pending=True, created__lte=timezone.now() - timedelta(hours=6)).all().delete() (edited)
```

**Comment by Klona13** [comment]
Created an account "CoolCat".
Waiting now...

**Comment by Klona13** [comment]
Ok the trcustoms source account is now deleted sucessfully.

Now I made a fake CoolCat with a fake trle.net ID (and source).
Then I registered for that account.
Now waiting to see what gets deleted.

**Comment by Klona13** [comment]
^For some reason the entire account was deleted after the cleanup, even though it was set to TRLE.NET source.

This means that if someone registers to claim a trle.net profile and then DOESN'T activate the email, the whole user disappears from the user list.

Instead, what should happen is that if the user is a trle.net source, the following fields only should be purged (the ones input on the registration form):
- Password
- First name
- Last name
- Email address
- Country

And uncheck pending activation.

This should restore the trle.net source account to its original pre-registration state.

**Comment by rr-** [comment]
@Klona13 can you confirm if this person had any level, news or  review associated with their mail accounts? Because if not, they will have their account deleted invariably.

**Comment by Klona13** [comment]
Ok I did this trle.net profile simulation and uploaded 1 level for this user:
![image](https://user-images.githubusercontent.com/93257509/158039665-131c4256-a1aa-430a-a0a0-fb4cf5096b25.png)

The registration should be cleared but the user page / profile should stay when the clean up happens

**Comment by rr-** [comment]
I need to clear also the email because of technical reasons.

We had a small leak in our design that is hard to describe but had a lot of nuances regarding deactivation/rejection.

To fix that leak and preserve authorship information, I do not distinguish between TRC and TRLE accounts anymore. When rejecting an account, I choose to delete it only if it has some no associated levels. If it does, I wipe it instead. This applies both to manual and automatic rejection.

So:

- Deactivate = set the account back to pending activation, make it impossible to log in
- Reject = if the account has some levels or reviews (= old TRLE accounts AND ALSO established TRCustoms account), wipe the account. Otherwise delete it. Show this only if the account is pending activation.

I changed the acquiring mechanism to allow acquiring also wiped accounts to be consistent.

Scenarios for you to test:

### Scenario 1

1. Look at old TRLE account.
    - It should not be possible to deactivate or delete the account.

### Scenario 2

1. Acquire a TRLE account that has no levels or reviews
2. As a moderator, deactivate it.
    - It should create an audit log.
    - It should set it back to pending activation but not wipe anything.
    - It should not be possible to log in using this account.
3. As a moderator, reject it.
    - It should create an audit log.
    - It should completely delete the account information.
    - It should no longer show the user in the user list.
    - It should not be possible to log in using this account.

### Scenario 3

1. Acquire a TRLE account that has some levels
2. As a moderator, deactivate it.
    - It should create an audit log.
    - It should set it back to pending activation but not wipe anything.
    - It should not be possible to log in using this account.
3. As a moderator, reject it.
    - It should create an audit log.
    - It should wipe the account information.
    - It should keep the account levels and reviews and the authorship information.
    - It should still show the user in the user list.
    - It should not be possible to log in using this account.
    - It should not be possible to deactivate or delete the account.

### Scenario 4

1. Create a new TRCustoms account, but do not add any levels or reviews
2. As a moderator, deactivate it.
    - It should create an audit log.
    - It should set it back to pending activation but not wipe anything.
    - It should not be possible to log in using this account.
3. As a moderator, reject it.
    - It should create an audit log.
    - It should completely delete the account information.
    - It should no longer show the user in the user list.
    - It should not be possible to log in using this account.

### Scenario 5

1. Create a new TRCustoms account and add some review or level
2. As a moderator, deactivate it.
    - It should create an audit log.
    - It should set it back to pending activation but not wipe anything.
    - It should not be possible to log in using this account.
3. As a moderator, reject it.
    - It should create an audit log.
    - It should wipe the account information.
    - It should keep the account levels and reviews and the authorship information.
    - It should still show the user in the user list.
    - It should not be possible to log in using this account.
    - It should not be possible to deactivate or delete the account.

### Scenario 6

1. Take any TRCustoms or TRLE account that has no reviews or levels
2. Change the email
3. Wait 6 hours for the automatic account removal
    - It should create an audit log.
    - It should completely delete the account information.
    - It should no longer show the user in the user list.
    - It should not be possible to log in using this account.

### Scenario 7

1. Take any TRCustoms or TRLE account that has some reviews or levels
2. Change the email
3. Wait 6 hours for the automatic account removal
    - It should create an audit log.
    - It should wipe the account information.
    - It should keep the account levels and reviews and the authorship information.
    - It should still show the user in the user list.
    - It should not be possible to log in using this account.
    - It should not be possible to deactivate or delete the account.

**Comment by Klona13** [comment]
Scenario 2
I could not find a trle.net account that has 0 levels and 0 reviews
I tested a user that only had reviews. Correct?

Scenario 2.3
Also: after rejecting in step 3, these fields remained. Shouldn't they be cleared as the email is also cleared?
![image](https://user-images.githubusercontent.com/93257509/158687218-ec09a1ae-5f9f-47b7-a6b1-8d908091aaa4.png)

Scenario 3.3
Same issue from scenario 2.3, the 2 fields aren't cleared after rejection.

Scenario 5.3
same fields not cleared when rejected^

Scenarios 6 and 7 are pending the 6 hours.

**Comment by Klona13** [comment]
Ok 6 and 7 are working as intended.

Testing 8 now.

**Comment by Klona13** [comment]
I registered as AODfan to claim the account at around 2:40 AM.
Didn't confirm my email and it was auto-rejected at exactly 3:00 AM.

**Comment by Klona13** [comment]
Testing:
Astraf
AODfan
[8:17 p.m.]
