### ISSUE TITLE
Level list sorting refactor

### ISSUE THREAD

**Issue by Klona13** [rr-/TRCustoms#236]
(Up and Down arrows buttons) Sort by:
Name
Release
Update
Rating
Downloads
Size

The up and down arrows are for ascending and descending. The default sorting type is Descending to show the biggest or latest number.

**Comment by rr-** [comment]
I don't get this, how do I show which sorting direction is active if using buttons?

**Comment by Klona13** [comment]
Something like this next to the dropdown menu
![image](https://user-images.githubusercontent.com/93257509/192102005-5b3b3293-022a-4b7f-ab06-8db77ca54c43.png) 
![image](https://user-images.githubusercontent.com/93257509/192101999-c06bc68b-0590-4516-920b-c8806b19aa4d.png)

**Comment by Klona13** [comment]
Ascending
![image](https://user-images.githubusercontent.com/93257509/192118079-263f6b6c-bafe-486a-b97d-ac76bb2c2fa4.png)
Descending
![image](https://user-images.githubusercontent.com/93257509/192118081-f34403b3-ffc3-4138-98be-194feda11fba.png)

**Comment by rr-** [comment]
OK I see. There are a couple of problems with this design.

- The intent of the button is not really clear in my opinion. Not many people will understand this without stopping and thinking what's this about.
- As always with the toggle button, it's not clear if it displays the current value or the action performed. In other words if the button label spells A-Z ↓, it's not clear if it means that A-Z ↓ is currently active, or if it means that clicking the button will set it to A-Z ↓.
- To change the sort direction I need to perform two searches instead of just 1 (click the button twice, not once).
- It's not immediately clear how this applies to certain values. What does A-Z ↓ mean: that the earliest, or the newest levels will be first? That the highest, or lowest rated levels will be at the top? This is why icon packs usually distribute icons that represent volumetric values with bars, and numeric values with 0-9. At the same time changing the icon depending on the dropdown value is a huge no-no.
- I struggle with understanding how "descending" and "ascending" applies to my search results, even with icon representations. I always have to stop and think for a moment, or I just resort things until the results look like I want. This is poor experience; it requires less mental effort to just select "Newest first" and press "search" instead of composing your search out of two elements "Last update" then "descending". I think that this is why all online shops I know (allegro.pl, ebay.com, amazon.de, rakuten.co.jp) have the kind of dropdown that we currently have.

Based on these thoughts I believe this is a step back.

**Comment by Klona13** [comment]
The purpose of this is to prevent the list from becoming too long (12 if we go by your idea and 6 with mine).
It's hard to wrap the logic around my idea as you've said as it would require a bit more thinking.

It's sacrificing a bit of user experience for a more fleshed out look, but really after the first 2-3 times of using it people will know how to use it. And it would encourage people to see what it does... kind of like exploration. :))

**Comment by rr-** [comment]
I think that no user wants to learn how to use a particular website. This approach takes more space, but allows for quick visual scanning. Common prefixes make the scanning just as quick as if it were single items, perhaps even slightly faster.

**Comment by Klona13** [comment]
That's the point of it. Visual scanning takes longer than just pressing a button to get what you want.
Especially since they're being renamed from something like:
Largest size or Size (large first)
To just:
Size
And then you get the button that's almost self explanatory. It's not completely vague as to what it actually does.
Name (Alphabetically first)
Release (Latest first)
Update (Last updated)
Rating (Highest first)
Download count (Highest first)
Size (Biggest first)

Putting repetitive information like this is very ugly.

**Comment by rr-** [comment]
But it's not just pressing a button to get what you want. You need to select what you want to sort on. For this, you need a visual scan _anyway_. Then you need to select Ascending or Descending. You need to pause for a moment to understand what this means. It takes longer. And this is why Amazon and other big players are not doing it this way.

In my opinion fewer, more common widgets are less ugly than this multi-state custom button that's supposed to accomplish a pretty common thing (sorting) and breaks POLA; plus my other points from the previous post still stand.

**Comment by Klona13** [comment]
Ok we can go with your way and we'll see how it will turn out.
But bear in mind that the "big players" don't have 12 items on the dropdown list:
![image](https://user-images.githubusercontent.com/93257509/194835710-e79007af-8116-44ad-9c2d-66fa35823702.png)

**Comment by rr-** [comment]
Yes, that is another point – do all of those sorting options make sense?
In my opinion only these make sense:

| Name | Why |
| --- | --- |
| Release: newest first | default, to play new levels |
| Release: oldest first | to play all levels |
| Average rating | (best to worst) to play popular levels, first criterion |
| Downloads: popular first | to play popular levels, second criterion |
| Downloads: unpopular first | to play hipster levels, first criterion |
| Least reviews | to play hipster levels, second criterion |

Things I think are not useful:
- Update date. It's only useful to people who want to replay mediocre levels after each update, and I don't think there are many of such players. Good levels will be remembered as good even without the updates. Mediocre levels I think will be forgotten in favor of better levels. Friend circles such as Sabatu releasing a new version of his TR1, will still primarily talk in Discord "hey please test this new version". Even if someone is interested in following new versions of each level, we don't force the authors to keep changelogs, so it still isn't a very useful feature.
- Name A-Z, and for sure Z-A. I suppose it's there for the people who want to play _all_ levels. But suppose it took them 2 years to clear levels starting with A-G, during those years new levels popped up with names starting with those letters, invalidating their quest. To that end it's better to use release date oldest→newest. The other scenario is to look for a level starting with a certain prefix, but to that end we can use search.
- Size. I don't understand why this matters, if we want long levels, we should use the length criterion, if we want heavy visually levels, that's not really a good way to measure this (raw wav music for example would explode the size). I'd make this into a new, separate filter "max size: 100 mb" "min size: 500 mb"

**Comment by Klona13** [comment]
Can we go by
- Latest Release
- Oldest Release
- Best Rated
- Worst Rated
- Most downloaded
- Least downloaded
- Biggest Size
- Smallest Size

It's fun to see which levels are the biggest, some times people pick based on that. I agree with the rest.

We should get rid of "Least reviews" too cause this page achieves that:
https://trcustoms.org/reviews/level_suggestions

 With this, we have 8!

**Comment by Klona13** [comment]
Would it be possible to fit levels with "not enough ratings" between slightly negative and mixed?
So this doesn't happen:
![image](https://user-images.githubusercontent.com/93257509/210156348-fb74a27a-a1e6-4aa9-bdb5-de3879f36331.png)

**Comment by Klona13** [comment]
Actually, "Biggest size" is fine cause the "no download" levels display at the last pages...
@rr- So we may able to solve "Smallest size" if this is possible: when that option is selected, levels with "no download" will be shown at the end (last pages) instead.
